name: funpy
channels:
  - conda-forge
dependencies:
  - matplotlib>=3.5
  - numpy>=1.17
  - scipy>=1.6
  - netcdf4
  # - cv2
  - xarray
  - dask
  # - cartopy>=0.20
  # - nc-time-axis
  # - geojson
  # - ffmpeg
  # - pyproj>=2.3
  # - libgdal>=3.1
  # - gdal>=3.1
  # - cfgrib
  # - pygrib
  # - xhistogram
  # - requests
  # - pytest
  # - pytest-cov
  # - pytest-benchmark
  # - pytest-mpl
  # - pynucos>=2.12
  # - isodate
  # - coloredlogs
  # - cmocean
  # - utm
  # - roaring-landmask>=0.7
  # - trajan>=0.1.3
  # - pip
  # - pip:
    # - motuclient
    # - pytest-sphinx
